name: Build Meguca
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: meguca
          path: ./meguca
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: www
