name: Build Meguca
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            pkg-config \
            libpth-dev \
            libwebp-dev \
            libopencv-dev \
            libgeoip-dev geoip-database \
            python3 python3-requests \
            git lsb-release wget curl netcat postgresql-client gzip
      - name: Build
        run: make
      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: meguca
          path: ./meguca
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: www
